name: check

on: ["pull_request"]

jobs:
  lint-coverage-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    name: Node ${{ matrix.node-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing dev dependencies
        run: npm ci

      - name: Checking rules
        run: npm run check-rules

      - name: Linting
        run: npm run lint
